source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ChatSDKSwift' do

  pod "ChatSDK/UI", '~> 5.0.10'
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/Upload"
  pod "ChatSDKFirebase/Push"
  pod "ChatSDKFirebase/FirebaseUI"
	
  #### Optional ####

  # Crashlytics see: https://firebase.google.com/docs/crashlytics/get-started?authuser=0

#   pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  
end
