source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ChatSDKSwift' do

  pod "ChatSDK", :path => "../"
  pod "ChatSDKFirebase/Adapter", :path => "../"
  pod "ChatSDKFirebase/FileStorage", :path => "../"
  pod "ChatSDKFirebase/Push", :path => "../"
#   pod "ChatSDKFirebase/SocialLogin", :path => "../"
#   pod "ChatSDKFirebase/FirebaseUI", :path => "../"

  #pod "ChatSDKModules/StickerMessage", :path => "../ChatSDKModules"
  #pod "ChatSDKModules/KeyboardOverlayOptions", :path => "../ChatSDKModules"
  #pod "ChatSDKModules/ContactBook", :path => "../ChatSDKModules"
  
end
