source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ChatSDKSwift' do
  
  pod "ChatSDK/Core", :podspec => "../ChatSDK"
  pod "ChatSDK/CoreData", :podspec => "../ChatSDK"
  pod "ChatSDK/FirebaseAdapter", :podspec => "../ChatSDK"
  
#   pod "ChatSDKUI", :podspec => "../ChatSDK/ChatSDKUI"
#   pod "ChatSDKCoreData", :podspec => "../ChatSDK/ChatSDKCoreData"
#   pod "ChatSDKFirebaseAdapter", :podspec => "../ChatSDK/ChatSDKFirebaseAdapter"
	
#   pod "ChatSDKFirebase/TypingIndicator", :path => "../../ChatSDK/ChatSDKFirebase"
#   pod "ChatSDKFirebase/VideoMessages", :path => "../../ChatSDK/ChatSDKFirebase"
#   pod "ChatSDKFirebase/AudioMessages", :path => "../../ChatSDK/ChatSDKFirebase"
#   pod "ChatSDKFirebase/ContactBook", :path => "../../ChatSDK/ChatSDKFirebase"
#   pod "ChatSDKFirebase/ReadReceipts", :path => "../../ChatSDK/ChatSDKFirebase"
#   pod "ChatSDKFirebase/NearbyUsers", :path => "../../ChatSDK/ChatSDKFirebase"

#   pod "TwoFactorAuth", :path => "../../ChatSDK/TwoFactorAuth"

#   pod "ChatSDKModules/StickerMessages", :path => "../../ChatSDK/ChatSDKModules"
#   pod "ChatSDKModules/KeyboardOverlayOptions", :path => "../../ChatSDK/ChatSDKModules"
	
#   pod 'GoogleSignIn'
#   pod 'TwitterKit'
#   pod 'FBSDKLoginKit'
#   pod 'Backendless'
	
end
