source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ChatSDKSwift' do

  pod "ChatSDK"
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/FileStorage"
  pod "ChatSDKFirebase/Push"
  pod "ChatSDKFirebase/SocialLogin"
  
end
