source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!

target 'ChatSDKSwift' do

  pod "ChatSDK"
  pod "ChatSDKFirebase/Adapter"
  pod "ChatSDKFirebase/FileStorage"
  pod "ChatSDKFirebase/Push"
  
end
