source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true
platform :ios, 13.0

target 'ChatSDKSwift' do

  pod "ChatSDK", :path => "../"
  pod "ChatSDKFirebase/Adapter", :path => "../"
  pod "ChatSDKFirebase/Upload", :path => "../"
  pod "ChatSDKFirebase/Push", :path => "../"
  pod "ChatSDKFirebase/FirebaseUI", :path => "../"

  pod "ChatSDKPro/ContactBook", :path => "../"
  pod "ChatSDKPro/Encryption", :path => "../"
  pod "ChatSDKPro/Firebase", :path => "../"
  pod "ChatSDKPro/FirebaseNearbyUsers", :path => "../"
  pod "ChatSDKPro/Message", :path => "../"
#  pod "ChatSDKPro/ChatK!t", :path => "../"

  pod "ChatK!t", :path => "../"
  pod "ChatK!t/ChatSDK", :path => "../"
  
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_LDFLAGS'] = '$(inherited)'
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = "YES"
            
            
        end
    end
end
