source 'https://github.com/CocoaPods/Specs.git'

target 'ChatSDK Demo' do

  use_frameworks!
  
  pod "ChatSDKCore”, :path => "../"
  pod "ChatSDKUI”, :path => "../"
  pod "ChatSDKCoreData”, :path => "../"
  pod "ChatSDKFirebaseAdapter”, :path => "../"

  #pod "ChatSDKModules/Backendless", :path => "ChatSDKModules"
	
end
