source 'https://github.com/CocoaPods/Specs.git'

target 'ChatSDK Demo' do
  
  pod "ChatSDK", :path => "../"
  pod "ChatSDKModules/Backendless", :path => "../../ChatSDK/ChatSDKModules"
  pod "ChatSDKFirebase/SocialLogin", :path => "../../ChatSDK/ChatSDKFirebase"
	
end
