source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'ChatKitDemo' do

  # pod "ChatSDK/UI", :path => "../"
  pod "ChatK!t", :path => "../"
  pod "ChatK!t/ChatSDK", :path => "../"
  pod "LoremIpsum"
  
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['OTHER_LDFLAGS'] = '$(inherited)'
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
end
